# Generated by Django 5.0.4 on 2024-04-25 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Taxi',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('plate', models.CharField(max_length=10, verbose_name='plate')),
            ],
        ),
    ]
